name: admin_sahu_talai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  cloud_firestore: 4.5.1
  firebase_storage: 11.2.1
  google_fonts: 4.0.4
  eva_icons_flutter: 3.1.0
  connectivity_plus: 4.0.1
  file_picker: 5.2.11
  firebase_auth: 4.6.1
  awesome_dialog: 3.1.0
  fluttericon: 2.0.0
  flutter_easyloading: 3.0.5
  tuple: 2.0.1
  just_audio: 0.9.34
  audioplayers: 4.1.0
  lottie: 2.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

