name: admin_sahu_talai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  cloud_firestore: 4.5.1
  firebase_storage: 11.2.1
  flutter_screenutil: 5.8.2
  google_fonts: 4.0.4
  paginate_firestore: 1.0.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

