// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcXOgcXcaZ2m4XCilx8-dKw9G2LQxrnQ',
    appId: '1:437159689669:web:837536971590cd992d1fac',
    messagingSenderId: '437159689669',
    projectId: 'kamussahutalai',
    authDomain: 'kamussahutalai.firebaseapp.com',
    storageBucket: 'kamussahutalai.appspot.com',
    measurementId: 'G-41BG86XB15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtfNXh9sAYXkUgHaQig-su6rxjG2uN_LE',
    appId: '1:437159689669:android:7e94667b3316858d2d1fac',
    messagingSenderId: '437159689669',
    projectId: 'kamussahutalai',
    storageBucket: 'kamussahutalai.appspot.com',
  );
}
